spring.application.name=Hr-and-payroll-management-system-backend
        
# ===============================
# LOCAL DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/payroll
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# SERVER
server.address=0.0.0.0
server.port=8080

# JWT & Admin Config
app.admin.email=admin@gmail.com
app.admin.password=1234
